### PR TITLE
Fixing FormatException on some locales other than English

### PR DESCRIPTION
**Pull request by stopiccot**
On some locales other than English (for example Russian) you can get such exception when building player:

```
FormatException: Input string was not in a correct format.
System.Number.ParseDouble (System.String value, System.Globalization.NumberStyles options, System.Globalization.NumberFormatInfo numfmt)
System.Double.Parse (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info)
System.Double.Parse (System.String s)
MoPubInternal.Editor.Postbuild.MoPubPostBuildiOS.CheckiOSVersion ()
MoPubInternal.Editor.Postbuild.MoPubPostBuildiOS.OnPostprocessBuild (UnityEditor.BuildTarget buildTarget, System.String buildPath) 
```

### CODE REVIEW

**Comment by patrickkulling** [comment]
Can this be addressed & fixed in an upcoming 5.5.x release please?

Best,
Patrick

**Comment by chauduyphanvu1** [comment]
Thank you for the PR! We'll take a look and see what can be done.

@stopiccot - do you have any reliable steps/workflow to trigger that Exception so we can test it out?

**Comment by stopiccot** [comment]
@chauduyphanvu1 just set your macOS language to Russian and try to export iOS unity project that is using mopub

**Comment by chauduyphanvu1** [comment]
@stopiccot - this script has been removed as of the 5.6.0 Unity SDK release. We are now using CocoaPods to fetch the iOS SDK. Let us know if you continue seeing the issue!

**Comment by sayiliromer** [comment]
I think this is not the only problem. There could be similar issues like that. 
https://github.com/mopub/mopub-unity-sdk/issues/57

**Comment by aornelas** [comment]
thanks for reporting!

fixed in the [5.7.0 release](https://github.com/mopub/mopub-unity-sdk/releases/tag/v5.7.0)

**Pull request closed without merging**
